### ISSUE TITLE
[BUG] Problema de Responsividade e Ajustes de Layout

### ISSUE THREAD

**Issue by Frotas** [Squad-61/ReCreio_WebSite#18]
**Descreva o Bug**
Algumas páginas não estão totalmente responsivas para dispositivos móveis, além de não está adaptável a dispositivos com resolução maior que a de um tablet.

**Comportamento esperado**
Adaptabilidade das páginas de acordo com a resolução do dispositivo.
A brand não está se comportando como o esperado, uma solução para este problema seria tornar sua posição absoluta e ajustar as propriedades para se adaptar a resoluçao maiores.
Alguns links não estão redirecionado para a página correta.

## TaskList:
- [ ] Responsividade
   - [ ] Brand não adaptável
- [x] Links incorretos
   - [ ] ...

**Comment by Guimillen** [comment]
Guilherme, depois vc pode me mostrar onde ainda está com a responsividade quebrada ou fora de resolução ?

**Comment by Frotas** [comment]
> Guilherme, depois vc pode me mostrar onde ainda está com a responsividade quebrada ou fora de resolução ?

Bom dia @Guimillen !
Ainda não consegui realizar todas as adaptações necessárias para a responsividade do site, estou fazendo alguns testes no layout.
