### ISSUE TITLE
[Feat] CADASTRO

### ISSUE THREAD

**Issue by Guimillen** [Squad-61/ReCreio_WebSite#22]
Precisamos criar tanto a página (HTML) de cadastro, quanto o back-end (modelos, classes java, BDs, tabelas etc).

(?) o cadastro pode ser dividido em 3 classes hierárquicas: 1. Professor > 2. Pais > 3. Alunos;

(?) O que deve conter no cadastro '1. Professor' :
Nome
ID Professor (PK)
RG
CPF 
Endereço (?)
Instituição de Ensino
Titulação
Turmas

(?) O que deve conter no cadastro '2. Pais' :

Nome do Pai/responsável
ID Pais/responsável (PK)
ID Professor (FK)
RG
CPF
Endereço (?)
Nome do Filho(s)
Instituição de Ensino
Turma(s)
Professor(es)

(?) O que deve conter no cadastro '3. Alunos' :

Nome
ID Aluno
ID Pais/responsável (FK)
Instituição de ensino:
Turma
Professor

**Comment by Guimillen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criando nossa página de cadastro](https://trello.com/c/rAlOH3L7/13-criando-nossa-p%C3%A1gina-de-cadastro)

**Comment by niasbezerra** [comment]
oiii, eu criei a pagina de cadastro na nossa primeira entrega, vcs não chegaram a ver? eu e  guilherme frotas tentamos d todas as formas dar o publish mas n sei uq deu nao conseguimos.... ver ai no link

https://github.com/niasbezerra/Tela-de-cadastro-Recreio

https://niasbezerra.github.io/Tela-de-cadastro-Recreio/
