### ISSUE TITLE
[FEAT] Atualização do Front-End

### ISSUE THREAD

**Issue by rebecafrutuoso** [Squad-61/ReCreio_WebSite#26]
Nesta atualização do front-end, foi realizado uma alteração na palheita de cores do site, navbar, footer,  ajuste na responsividade e  nas páginas:

  - Index
  - Quem somos
  - Feed
  - Cadastro
  - Contato
 
No index, foi realizado a criação de um carousel que mostra as novidades e post das demais páginas do site.
Também foi adicionado cards que mostram  e redirecionam para as postagem realizados na página "Feed".

Em "Quem Somos", foi realizado a publicação do texto explicado sobre o projeto e a criação de imagens ilustrativas.

No "Feed", foi realizado a criação de cards que se assimilam a publicações de reportagens e tem a função de trazer interatividade 
e novidades do que tem sido realizado no projeto.

Em  "Contato", foi criado uma formulário e adicionados os meios de comunicações.

Em "Cadastro" foi realizado o ajuste somente no navbar e footer.

**Comment by Guimillen** [comment]
Revisamos juntos
